author:
  name:wyf
  age:32

---

#logging:
#  file:/src/main/resources/mylog/log.log
#  level:
#    org:
#      springframework:
#        web:DEBUG

spring:
  profiles:
    active: dev

#可以在控制台查看开启了那些自动配置
debug: false
